/**
 * ============================================
 * Sui-Unlock Configuration Auto-Update Script
 * ============================================
 * 
 * This script automatically extracts the Package ID from deploy-output.json
 * and updates all configuration files to use the new ID.
 * 
 * Usage:
 *   npx tsx scripts/update-config.ts
 * 
 * Or via npm script:
 *   npm run post-deploy
 * 
 * What it updates:
 *   - .env.local (NEXT_PUBLIC_MARKET_PACKAGE_ID)
 *   - scripts/verify-logic.ts (PACKAGE_ID constant)
 */

import * as fs from 'fs';
import * as path from 'path';

// ============================================
// CONFIGURATION
// ============================================

const ROOT_DIR = path.resolve(__dirname, '..');
const DEPLOY_OUTPUT_PATH = path.join(ROOT_DIR, 'deploy-output.json');
const ENV_LOCAL_PATH = path.join(ROOT_DIR, '.env.local');
const VERIFY_SCRIPT_PATH = path.join(ROOT_DIR, 'scripts', 'verify-logic.ts');

// ============================================
// HELPER FUNCTIONS
// ============================================

interface ObjectChange {
  type: string;
  packageId?: string;
  objectId?: string;
  objectType?: string;
}

interface DeployOutput {
  objectChanges?: ObjectChange[];
  effects?: {
    created?: Array<{
      reference?: { objectId: string };
      owner?: { Immutable?: boolean } | string;
    }>;
  };
}

function extractPackageId(deployOutput: DeployOutput): string | null {
  // Method 1: Look for "published" type in objectChanges
  if (deployOutput.objectChanges) {
    for (const change of deployOutput.objectChanges) {
      if (change.type === 'published' && change.packageId) {
        return change.packageId;
      }
    }
  }

  // Method 2: Look for immutable object (package) in effects.created
  if (deployOutput.effects?.created) {
    for (const created of deployOutput.effects.created) {
      const owner = created.owner;
      if (typeof owner === 'object' && owner && 'Immutable' in owner) {
        if (created.reference?.objectId) {
          return created.reference.objectId;
        }
      }
    }
  }

  // Method 3: Look for package type in objectChanges
  if (deployOutput.objectChanges) {
    for (const change of deployOutput.objectChanges) {
      if (change.objectType?.includes('::package::') || change.type === 'created') {
        if (change.objectId && change.objectId.length === 66) {
          // Check if it looks like a package (usually first created object)
          return change.objectId;
        }
      }
    }
  }

  return null;
}

function updateEnvLocal(packageId: string): boolean {
  try {
    let content: string;
    
    // Check if file exists
    if (fs.existsSync(ENV_LOCAL_PATH)) {
      content = fs.readFileSync(ENV_LOCAL_PATH, 'utf-8');
    } else {
      // Create new file with default content
      content = `# Sui-Unlock Environment Variables
# Auto-generated by update-config.ts

# Sui Network
NEXT_PUBLIC_SUI_NETWORK=testnet

# Smart Contract Package ID
NEXT_PUBLIC_MARKET_PACKAGE_ID=${packageId}

# Walrus Protocol
NEXT_PUBLIC_WALRUS_PUBLISHER=https://publisher.walrus-testnet.walrus.space
NEXT_PUBLIC_WALRUS_AGGREGATOR=https://aggregator.walrus-testnet.walrus.space
`;
      fs.writeFileSync(ENV_LOCAL_PATH, content);
      console.log('   📄 Created new .env.local file');
      return true;
    }
    
    // Check if NEXT_PUBLIC_MARKET_PACKAGE_ID exists (handle comments, whitespace)
    // Match: NEXT_PUBLIC_MARKET_PACKAGE_ID=value (with optional whitespace and comments)
    const packageIdRegex = /NEXT_PUBLIC_MARKET_PACKAGE_ID\s*=\s*[^\r\n]*(?:\r?\n|$)/;
    
    if (packageIdRegex.test(content)) {
      // Replace existing value (preserve line ending)
      content = content.replace(
        packageIdRegex,
        (match) => {
          // Preserve the line ending (newline or end of file)
          const lineEnding = match.includes('\r\n') ? '\r\n' : (match.includes('\n') ? '\n' : '\n');
          return `NEXT_PUBLIC_MARKET_PACKAGE_ID=${packageId}${lineEnding}`;
        }
      );
    } else {
      // Add new line at the end
      if (!content.endsWith('\n')) {
        content += '\n';
      }
      content += `NEXT_PUBLIC_MARKET_PACKAGE_ID=${packageId}\n`;
    }
    
    fs.writeFileSync(ENV_LOCAL_PATH, content);
    return true;
  } catch (error) {
    console.error('   ❌ Failed to update .env.local:', error);
    return false;
  }
}

function updateVerifyScript(packageId: string): boolean {
  try {
    if (!fs.existsSync(VERIFY_SCRIPT_PATH)) {
      console.log('   ⚠️  verify-logic.ts not found, skipping');
      return true;
    }
    
    let content = fs.readFileSync(VERIFY_SCRIPT_PATH, 'utf-8');
    
    // Replace PACKAGE_ID constant
    const packageIdRegex = /const PACKAGE_ID = "[^"]*"/;
    
    if (packageIdRegex.test(content)) {
      content = content.replace(
        packageIdRegex,
        `const PACKAGE_ID = "${packageId}"`
      );
      fs.writeFileSync(VERIFY_SCRIPT_PATH, content);
      return true;
    } else {
      console.log('   ⚠️  PACKAGE_ID constant not found in verify-logic.ts');
      return false;
    }
  } catch (error) {
    console.error('   ❌ Failed to update verify-logic.ts:', error);
    return false;
  }
}

// ============================================
// MAIN FUNCTION
// ============================================

async function main() {
  console.log('');
  console.log('🔧 Sui-Unlock Configuration Auto-Update');
  console.log('========================================');
  console.log('');

  // Step 1: Read deploy-output.json
  console.log('📖 Reading deploy-output.json...');
  
  if (!fs.existsSync(DEPLOY_OUTPUT_PATH)) {
    console.error('');
    console.error('❌ Error: deploy-output.json not found!');
    console.error('   Please run ./deploy.sh first to deploy the contract.');
    console.error('');
    process.exit(1);
  }

  // Read raw file content
  const rawContent = fs.readFileSync(DEPLOY_OUTPUT_PATH, 'utf-8').trim();
  
  // Check if file is empty or only contains whitespace
  if (!rawContent || rawContent.length === 0) {
    console.error('');
    console.error('❌ Error: deploy-output.json is empty!');
    console.error('   The deployment may have failed or produced no output.');
    console.error('   Please check deploy-errors.log for details.');
    console.error('');
    process.exit(1);
  }
  
  // Step 1.5: Sanitize input - extract only JSON portion
  console.log('   🔍 Extracting JSON from file...');
  
  const firstBraceIndex = rawContent.indexOf('{');
  const lastBraceIndex = rawContent.lastIndexOf('}');
  
  if (firstBraceIndex === -1 || lastBraceIndex === -1 || firstBraceIndex >= lastBraceIndex) {
    console.error('');
    console.error('❌ Error: Could not find valid JSON structure in deploy-output.json');
    console.error('   Expected to find { ... } but structure is invalid.');
    console.error('');
    
    // Check for common error patterns
    const hasAccessDenied = rawContent.toLowerCase().includes('erişim engellendi') || 
                           rawContent.toLowerCase().includes('access denied') ||
                           rawContent.toLowerCase().includes('os error 5');
    const hasPermissionError = rawContent.toLowerCase().includes('permission') ||
                              rawContent.toLowerCase().includes('denied');
    
    if (hasAccessDenied || hasPermissionError) {
      console.error('   🔍 Detected: File permission error (Access Denied)');
      console.error('');
      console.error('   Solutions:');
      console.error('   1. Run PowerShell/terminal as Administrator');
      console.error('   2. Check file permissions in contracts/sui_drop');
      console.error('   3. Close any programs that might be locking files');
      console.error('   4. Try running: Remove-Item deploy-output.json, deploy-errors.log -ErrorAction SilentlyContinue');
    } else {
      console.error('   This usually means:');
      console.error('   1. The deployment failed (check deploy-errors.log)');
      console.error('   2. The output was redirected incorrectly');
      console.error('   3. The file contains only warnings/errors');
    }
    
    console.error('');
    console.error('   First 200 characters of file:');
    console.error('   ' + '─'.repeat(60));
    const preview = rawContent.substring(0, 200).replace(/\n/g, '\\n');
    console.error('   ' + preview);
    if (rawContent.length > 200) {
      console.error('   ... (truncated)');
    }
    console.error('   ' + '─'.repeat(60));
    console.error('');
    
    // Check if deploy-errors.log exists
    const errorLogPath = path.join(ROOT_DIR, 'deploy-errors.log');
    if (fs.existsSync(errorLogPath)) {
      console.error('   📄 Check deploy-errors.log for full error details');
      console.error('');
    }
    
    // Platform-specific instructions
    const isWindows = process.platform === 'win32';
    if (isWindows) {
      console.error('   💡 On Windows, try running:');
      console.error('      .\\deploy.ps1');
      console.error('');
    } else {
      console.error('   💡 Try running: ./deploy.sh');
      console.error('');
    }
    
    process.exit(1);
  }
  
  // Extract JSON string
  const jsonString = rawContent.substring(firstBraceIndex, lastBraceIndex + 1);
  
  // Parse JSON
  let deployOutput: DeployOutput;
  try {
    deployOutput = JSON.parse(jsonString);
    console.log('   ✅ JSON extracted and parsed successfully');
    
    // Log if there was extra content
    if (firstBraceIndex > 0 || lastBraceIndex < rawContent.length - 1) {
      const prefixLength = firstBraceIndex;
      const suffixLength = rawContent.length - lastBraceIndex - 1;
      console.log(`   ℹ️  Removed ${prefixLength} chars before JSON and ${suffixLength} chars after`);
    }
  } catch (error) {
    console.error('');
    console.error('❌ Error: Failed to parse extracted JSON');
    console.error('   The JSON structure may be malformed.');
    console.error('');
    
    // Show debug info
    console.error('   Debug info:');
    console.error(`   - First { at index: ${firstBraceIndex}`);
    console.error(`   - Last } at index: ${lastBraceIndex}`);
    console.error(`   - Extracted JSON length: ${jsonString.length}`);
    console.error('');
    console.error('   First 200 characters of extracted JSON:');
    console.error('   ' + '─'.repeat(60));
    const preview = jsonString.substring(0, 200).replace(/\n/g, '\\n');
    console.error('   ' + preview);
    if (jsonString.length > 200) {
      console.error('   ... (truncated)');
    }
    console.error('   ' + '─'.repeat(60));
    console.error('');
    process.exit(1);
  }

  // Step 2: Extract Package ID
  console.log('');
  console.log('🔍 Extracting Package ID...');
  
  const packageId = extractPackageId(deployOutput);
  
  if (!packageId) {
    console.error('');
    console.error('❌ Error: Could not find Package ID in deploy-output.json');
    console.error('   Please check the file manually or redeploy.');
    console.error('');
    
    // Show raw objectChanges for debugging
    if (deployOutput.objectChanges) {
      console.log('   Debug - objectChanges:');
      deployOutput.objectChanges.forEach((change, i) => {
        console.log(`   [${i}] type: ${change.type}, packageId: ${change.packageId || 'N/A'}`);
      });
    }
    
    process.exit(1);
  }

  console.log(`   ✅ Package ID: ${packageId}`);

    // Step 3: Update .env.local
  console.log('');
  console.log('📝 Updating .env.local...');
  
  if (updateEnvLocal(packageId)) {
    console.log('   ✅ .env.local updated');
    
    // Verify the update worked
    try {
      const updatedContent = fs.readFileSync(ENV_LOCAL_PATH, 'utf-8');
      if (updatedContent.includes(`NEXT_PUBLIC_MARKET_PACKAGE_ID=${packageId}`)) {
        console.log('   ✅ Verification: Package ID correctly written');
      } else {
        console.log('   ⚠️  Warning: Update may not have worked correctly');
      }
    } catch (e) {
      console.log('   ⚠️  Could not verify update');
    }
  } else {
    console.error('   ❌ Failed to update .env.local');
    process.exit(1);
  }

  // Step 4: Update verify-logic.ts
  console.log('');
  console.log('📝 Updating scripts/verify-logic.ts...');
  
  if (updateVerifyScript(packageId)) {
    console.log('   ✅ verify-logic.ts updated');
  } else {
    console.log('   ⚠️  Could not update verify-logic.ts (may need manual update)');
  }

  // Success!
  console.log('');
  console.log('========================================');
  console.log('✅ Configuration updated successfully!');
  console.log('========================================');
  console.log('');
  console.log('📋 Summary:');
  console.log(`   Package ID: ${packageId}`);
  console.log('');
  console.log('🚀 Next steps:');
  console.log('   1. Restart your dev server: npm run dev');
  console.log('   2. Run verification: npm run verify');
  console.log('   3. Test the UI in your browser');
  console.log('');
}

// Run
main().catch((error) => {
  console.error('❌ Script failed:', error);
  process.exit(1);
});

